### ISSUE TITLE
Windows support (Again?)

### ISSUE THREAD

**Issue by Corgano** [nickelpro/spock#25]
I'm probably missing something here, but hear me out. I installed the dependencies as instructed, and got to the point where I should be able to run the demo, but I got this:

  File "C:\Python34\lib\site-packages\spock\plugins\core\net.py", line 55, in <module>
    rmask = select.POLLIN|select.POLLERR|select.POLLHUP
AttributeError: 'module' object has no attribute 'POLLIN'

I did a bit of googling and came up with this post:

http://stackoverflow.com/questions/22923063/cant-access-constant-pollin-from-select-module-with-python-2-7-or-3-3-on-windows

Which lead me back here, but before I posted I doubble checked other tickers and someone has also posted about windows support here:
https://github.com/nickelpro/spock/issues/8
The last post implies that windows support has been added, but It isn't working for me on windows 7? Is there a step I'm missing to enable windows support? Or was I mistaken?

My goal is to try and run this on a raspberry pi, but use windows for most my testing and whatnaught.

**Comment by nickelpro** [comment]
There is a definite chance Spock works on Windows now. I'm closing this until proven otherwise
