### ISSUE TITLE
Teams Packet something something error.

### ISSUE THREAD

**Issue by ScruffyRules** [nickelpro/spock#31]
http://scruffyrules.com/i/6fmh7S.txt

**Comment by nickelpro** [comment]
Two seperate issues here, one in the Teams packet decoding process, the other in NBT data decoder. Looking into both

**Comment by nickelpro** [comment]
Teams packet should be fixed in d90a0f9ffd83fd304ea11d6040d01589740e85a0

**Comment by nickelpro** [comment]
NBT data decoding/encoding maybe fixed in f8636dc89164529c4b3ef83b5aa78ea30987c7be
Please test

**Comment by nickelpro** [comment]
Reported as fixed, closing
